parsitter-name = "cs"
enabled = true
tree-sitter-scope = "source.cs"
file-extensions = [".cs"]
type-replacements = { COMMENT = "//comment", IDENTIFIER = "var", NUMBER = "0", STRING = "\"\"", VARIABLE = "x", BOOLEAN = "true", FUNCTION = "void F() { }"}
string-delim = "\""
