name: Documentation

on:
  push:
    branches:
      - 'master'
      - 'cc-improvements'
    tags: '*'
  pull_request:

jobs:
  build:
    # These permissions are needed to:
    # - Deploy the documentation: https://documenter.juliadocs.org/stable/man/hosting/#Permissions
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Install tree-sitter
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/tree-sitter/tree-sitter/releases/download/v0.25.0/tree-sitter-linux-x64.gz
          gunzip tree-sitter-linux-x64.gz
          chmod +x tree-sitter-linux-x64
          sudo mv tree-sitter-linux-x64 /usr/local/bin/tree-sitter
          tree-sitter --version
          mkdir ~/src/
      - name: Init tree-sitter
        run: |
          tree-sitter init-config
          cat ~/.config/tree-sitter/config.json
      - name: install tree-sitter-r
        run: |
          git clone https://github.com/r-lib/tree-sitter-r ~/src/tree-sitter-r
          cd ~/src/tree-sitter-r
          tree-sitter generate
      - name: install tree-sitter-python
        run: |
          git clone  https://github.com/tree-sitter/tree-sitter-python ~/src/tree-sitter-python
          cd ~/src/tree-sitter-python
          tree-sitter generate
      - name: install tree-sitter-julia
        run: |
          git clone https://github.com/tree-sitter/tree-sitter-julia ~/src/tree-sitter-julia
          cd ~/src/tree-sitter-julia
          tree-sitter generate
      - name: install tree-sitter-c
        run: |
          git clone https://github.com/tree-sitter/tree-sitter-c ~/src/tree-sitter-c
          cd ~/src/tree-sitter-c
          tree-sitter generate
      - name: install tree-sitter-csharp
        run: |
          git clone https://github.com/tree-sitter/tree-sitter-c-sharp ~/src/tree-sitter-c-sharp
          cd ~/src/tree-sitter-c-sharp
          tree-sitter generate
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - name: Build and deploy
        run: julia --color=yes --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
