name: Test

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install tree-sitter
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install -g tree-sitter-cli@0.25.10
      - name: Init tree-sitter
        run: tree-sitter init-config
      - name: install tree-sitter-r
        run: |
          git clone https://github.com/r-lib/tree-sitter-r 
          cd tree-sitter-r
          tree-sitter generate 
      - name: install tree-sitter-python
        run: |
          git clone  https://github.com/tree-sitter/tree-sitter-python
          cd tree-sitter-python
          tree-sitter generate
      - name: install tree-sitter-julia
        run: |
          git clone https://github.com/tree-sitter/tree-sitter-julia
          cd tree-sitter-julia
          tree-sitter generate
      - name: install tree-sitter-c
        run: |
          git clone https://github.com/tree-sitter/tree-sitter-c
          cd tree-sitter-c
          tree-sitter generate
      - name: install tree-sitter-csharp
        run: |
          git clone https://github.com/tree-sitter/tree-sitter-c-sharp
          cd tree-sitter-c-sharp
          tree-sitter generate
        continue-on-error: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Julia 1.x
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
